### ISSUE TITLE
No ckpt.meta file in the Google's release of 24 smaller BERT models

### ISSUE THREAD

**Issue by sauravpr** [prajjwal1/generalize_lm_nli#34]
Google's release of the 24 smaller BERT models at https://github.com/google-research/bert do not have the .meta file. For example, the bert-base model (https://storage.googleapis.com/bert_models/2020_02_20/uncased_L-12_H-768_A-12.zip) provided in the list does not the .meta file, while the original release of bert-base by Google at https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-12_H-768_A-12.zip contains the .meta file. Is the .meta file needed if we load the TF checkpoints in Pytorch using huggingface?

**Comment by prajjwal1** [comment]
`.meta` file is not needed if you want to load TF checkpoints in Pytorch. I have ported all the TF BERT models in Pytorch. If you follow the `README` closely, you can see that no files are required to be installed by user. If you want to use BERT models in Pytorch, then follow the README and you can follow-up if there are some unanswered query. If you want to use BERT with TF, then this is not the right place to discuss since this repository doesn't use TF. So you might want to head to Google's BERT repository or HF transformers.

**Comment by sauravpr** [comment]
Thanks, got it!
